// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTenantService.Persistence.DataBase;

#nullable disable

namespace MultiTenantService.Persistence.Migrations.MySQL
{
    [DbContext(typeof(OrgDbContext))]
    partial class OrgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MultiTenantService.Domain.Entities.Organizacion.OrganizacionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("FechaEliminacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid?>("UsuarioActualizacionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UsuarioEliminacionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Organizacion", "Organizacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTimeOffset(new DateTime(2024, 7, 4, 1, 59, 6, 497, DateTimeKind.Unspecified).AddTicks(8773), new TimeSpan(0, -6, 0, 0, 0)),
                            Nombre = "Organizacion1",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("MultiTenantService.Domain.Entities.Usuario.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("FechaEliminacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<Guid?>("UsuarioActualizacionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UsuarioEliminacionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Usuarios", "Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            FechaCreacion = new DateTimeOffset(new DateTime(2024, 7, 4, 1, 59, 6, 497, DateTimeKind.Unspecified).AddTicks(8927), new TimeSpan(0, -6, 0, 0, 0)),
                            OrganizacionId = 1,
                            Password = "Admin.123",
                            UserName = "Admin",
                            UsuarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("MultiTenantService.Domain.Entities.Usuario.UsuarioEntity", b =>
                {
                    b.HasOne("MultiTenantService.Domain.Entities.Organizacion.OrganizacionEntity", "Organizacion")
                        .WithMany("Usuario")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("MultiTenantService.Domain.Entities.Organizacion.OrganizacionEntity", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
